function Strings( config ) {

	var language = config.getKey( 'language' );

	var values = {
		ru: {
			'menubar/file': 'Файл',
			'menubar/file/new': 'Новый',
			'menubar/file/import': 'Импорт',
			'menubar/file/export/geometry': 'Экспорт геометрии',
			'menubar/file/export/object': 'Экспорт объектов',
			'menubar/file/export/scene': 'Экспорт сцены',
			'menubar/file/export/dae': 'Экспорт DAE',
			'menubar/file/export/drc': 'Экспорт DRC',
			'menubar/file/export/glb': 'Экспорт GLB',
			'menubar/file/export/gltf': 'Экспорт GLTF',
			'menubar/file/export/obj': 'Экспорт OBJ',
			'menubar/file/export/ply': 'Exporer PLY',
			'menubar/file/export/ply_binary': 'Экспорт PLY (двоичный)',
			'menubar/file/export/stl': 'Экспорт STL',
			'menubar/file/export/stl_binary': 'Экспорт STL (двоичный)',
			'menubar/file/publish': 'Публикация',

			'menubar/edit': 'Редактировать',
			'menubar/edit/undo': 'Назад (Ctrl+Z)',
			'menubar/edit/redo': 'Вперед (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': 'Очистить историю',
			'menubar/edit/clone': 'Клонировать',
			'menubar/edit/delete': 'Удалить',
			'menubar/edit/fixcolormaps': 'Исправить цветовые карты',

			'menubar/add': 'Добавить',
			'menubar/add/group': 'Группа',
			'menubar/add/plane': 'Плоскость',
			'menubar/add/box': 'Куб',
			'menubar/add/circle': 'Круг',
			'menubar/add/cylinder': 'Цилиндр',
			'menubar/add/ring': 'Кольцо',
			'menubar/add/sphere': 'Сфера',
			'menubar/add/dodecahedron': 'Додекаэдр',
			'menubar/add/icosahedron': 'Икосаэдр',
			'menubar/add/octahedron': 'Октаэдр',
			'menubar/add/tetrahedron': 'Тетраэдр',
			'menubar/add/torus': 'Тор',
			'menubar/add/tube': 'Труба',
			'menubar/add/torusknot': 'Узел Тора',
			'menubar/add/lathe': 'Пластичная модель',
			'menubar/add/sprite': 'Спрайт',
			'menubar/add/pointlight': 'Точечный свет',
			'menubar/add/spotlight': 'Прожектор',
			'menubar/add/directionallight': 'Нрправленный свет',
			'menubar/add/hemispherelight': 'Полусферический свет',
			'menubar/add/ambientlight': 'Окружающий свет',
			'menubar/add/perspectivecamera': 'Камера перспектива',
			'menubar/add/orthographiccamera': 'Ортографическая камера',

			'menubar/settings': 'Настройки',

			'menubar/status/autosave': 'Автосохранение',

			'menubar/play': 'Запустить',
			'menubar/play/stop': 'Остановить',
			'menubar/play/play': 'Запустить',

			'menubar/examples': 'Примеры',
			'menubar/examples/Arkanoid': 'Арканоид',
			'menubar/examples/Camera': 'Камера',
			'menubar/examples/Particles': 'Частицы',
			'menubar/examples/Pong': 'Понг',
			'menubar/examples/Shaders': 'Шейдеры',

			'menubar/help': 'Помощь',
			'menubar/help/source_code': 'Исходный код',
			'menubar/help/icons': 'Иконки',
			'menubar/help/about': 'Предложение',

			'sidebar/scene': 'Сцена',
			'sidebar/scene/background': 'Задний фон',
			'sidebar/scene/environment': 'Среда',
			'sidebar/scene/fog': 'Туман',

			'sidebar/properties/object': 'Объект',
			'sidebar/properties/geometry': 'Геометрия',
			'sidebar/properties/material': 'Материал',
			'sidebar/properties/script': 'Скрипт',

			'sidebar/object/type': 'Тип',
			'sidebar/object/new': 'Новый',
			'sidebar/object/uuid': 'UUID',
			'sidebar/object/name': 'Имя',
			'sidebar/object/position': 'Позиция',
			'sidebar/object/rotation': 'Поворот',
			'sidebar/object/scale': 'Размер',
			'sidebar/object/fov': 'Поле зрения',
			'sidebar/object/left': 'Лево',
			'sidebar/object/right': 'Право',
			'sidebar/object/top': 'Верх',
			'sidebar/object/bottom': 'Низ',
			'sidebar/object/near': 'Близко',
			'sidebar/object/far': 'Далеко',
			'sidebar/object/intensity': 'Интенсивность',
			'sidebar/object/color': 'Цвет',
			'sidebar/object/groundcolor': 'Основной цвет',
			'sidebar/object/distance': 'Дистанция',
			'sidebar/object/angle': 'Угол',
			'sidebar/object/penumbra': 'Полутень',
			'sidebar/object/decay': 'Распад',
			'sidebar/object/shadow': 'Тень',
			'sidebar/object/shadowBias': 'Смещение направленной тени',
			'sidebar/object/shadowNormalBias': 'Нормальное смещение тени',
			'sidebar/object/shadowRadius': 'Радиус тени',
			'sidebar/object/cast': 'Оттенок', // XXX хз на счет перевода
			'sidebar/object/receive': 'Получить', // XXX хз на счет перевода
			'sidebar/object/visible': 'Видимый',
			'sidebar/object/frustumcull': 'Усеченный',
			'sidebar/object/renderorder': 'Порядок рендеринга',
			'sidebar/object/userdata': 'Пользовательский данные',

			'sidebar/geometry/type': 'Тип',
			'sidebar/geometry/new': 'Новый',
			'sidebar/geometry/uuid': 'UUID',
			'sidebar/geometry/name': 'Имя',
			'sidebar/geometry/bounds': 'Границы',
			'sidebar/geometry/show_vertex_normals': 'Показать нормали',

			'sidebar/geometry/box_geometry/width': 'Ширина',
			'sidebar/geometry/box_geometry/height': 'Высота',
			'sidebar/geometry/box_geometry/depth': 'Глубина',
			'sidebar/geometry/box_geometry/widthseg': 'Сегменты по ширине',
			'sidebar/geometry/box_geometry/heightseg': 'Сегменты по высоте',
			'sidebar/geometry/box_geometry/depthseg': 'Сегменты по глубине',

			'sidebar/geometry/buffer_geometry/attributes': 'Атрибуты',
			'sidebar/geometry/buffer_geometry/index': 'Index',

			'sidebar/geometry/circle_geometry/radius': 'Радиус',
			'sidebar/geometry/circle_geometry/segments': 'Сегменты',
			'sidebar/geometry/circle_geometry/thetastart': 'Тета старт',
			'sidebar/geometry/circle_geometry/thetalength': 'Тета длина',

			'sidebar/geometry/cylinder_geometry/radiustop': 'Верхний радиус',
			'sidebar/geometry/cylinder_geometry/radiusbottom': 'Нижний радиус',
			'sidebar/geometry/cylinder_geometry/height': 'Высота',
			'sidebar/geometry/cylinder_geometry/radialsegments': 'Радиальные сегменты',
			'sidebar/geometry/cylinder_geometry/heightsegments': 'Сегменты высоты',
			'sidebar/geometry/cylinder_geometry/openended': 'Открытые концы',

			'sidebar/geometry/extrude_geometry/curveSegments': 'Сегменты кривой',
			'sidebar/geometry/extrude_geometry/steps': 'Шаг',
			'sidebar/geometry/extrude_geometry/depth': 'Глубина',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'Скос',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'Толщина',
			'sidebar/geometry/extrude_geometry/bevelSize': 'Размер фаски',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'Смещение фаски',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'Сегменты фаски',
			'sidebar/geometry/extrude_geometry/shape': 'Форма',

			'sidebar/geometry/geometry/vertices': 'Вершины',
			'sidebar/geometry/geometry/faces': 'Грань',

			'sidebar/geometry/dodecahedron_geometry/radius': 'Радиус',
			'sidebar/geometry/dodecahedron_geometry/detail': 'Детали',

			'sidebar/geometry/icosahedron_geometry/radius': 'Радиус',
			'sidebar/geometry/icosahedron_geometry/detail': 'Детали',

			'sidebar/geometry/octahedron_geometry/radius': 'Радиус',
			'sidebar/geometry/octahedron_geometry/detail': 'Детали',

			'sidebar/geometry/tetrahedron_geometry/radius': 'Радиус',
			'sidebar/geometry/tetrahedron_geometry/detail': 'Détail',

			'sidebar/geometry/lathe_geometry/segments': 'Сегменты',
			'sidebar/geometry/lathe_geometry/phistart': 'Phi старт',
			'sidebar/geometry/lathe_geometry/philength': 'Phi длина',
			'sidebar/geometry/lathe_geometry/points': 'Точки',

			'sidebar/geometry/plane_geometry/width': 'Ширина',
			'sidebar/geometry/plane_geometry/height': 'Высота',
			'sidebar/geometry/plane_geometry/widthsegments': 'Ширина сегментов',
			'sidebar/geometry/plane_geometry/heightsegments': 'Высота сегментов',

			'sidebar/geometry/ring_geometry/innerRadius': 'Внутренний радиус',
			'sidebar/geometry/ring_geometry/outerRadius': 'Внешний',
			'sidebar/geometry/ring_geometry/thetaSegments': 'Тета-сегменты',
			'sidebar/geometry/ring_geometry/phiSegments': 'Phi сегменты',
			'sidebar/geometry/ring_geometry/thetastart': 'Тета-старт',
			'sidebar/geometry/ring_geometry/thetalength': 'Тета-длина',

			'sidebar/geometry/shape_geometry/curveSegments': 'Сегменты кривой',
			'sidebar/geometry/shape_geometry/extrude': 'Выдавливать',

			'sidebar/geometry/sphere_geometry/radius': 'Радиус',
			'sidebar/geometry/sphere_geometry/widthsegments': 'Ширина сегментов',
			'sidebar/geometry/sphere_geometry/heightsegments': 'Высота сегментов',
			'sidebar/geometry/sphere_geometry/phistart': 'Phi старт',
			'sidebar/geometry/sphere_geometry/philength': 'Phi длина',
			'sidebar/geometry/sphere_geometry/thetastart': 'Тета-старт',
			'sidebar/geometry/sphere_geometry/thetalength': 'Тета-длина',

			'sidebar/geometry/torus_geometry/radius': 'Радиус',
			'sidebar/geometry/torus_geometry/tube': 'Труба',
			'sidebar/geometry/torus_geometry/radialsegments': 'Радиальные сегменты',
			'sidebar/geometry/torus_geometry/tubularsegments': 'Трубчатые сегменты',
			'sidebar/geometry/torus_geometry/arc': 'Дуга',

			'sidebar/geometry/torusKnot_geometry/radius': 'Радиус',
			'sidebar/geometry/torusKnot_geometry/tube': 'Труба',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': 'Трубчатые сегменты',
			'sidebar/geometry/torusKnot_geometry/radialsegments': 'Радиальные сегменты',
			'sidebar/geometry/torusKnot_geometry/p': 'P',
			'sidebar/geometry/torusKnot_geometry/q': 'Q',

			'sidebar/geometry/tube_geometry/path': 'Путь',
			'sidebar/geometry/tube_geometry/radius': 'Радиус',
			'sidebar/geometry/tube_geometry/tube': 'Труба',
			'sidebar/geometry/tube_geometry/tubularsegments': 'Трубчатые сегменты',
			'sidebar/geometry/tube_geometry/radialsegments': 'Радиальные сегменты',
			'sidebar/geometry/tube_geometry/closed': 'Закрыть',
			'sidebar/geometry/tube_geometry/curvetype': 'Тип кривой',
			'sidebar/geometry/tube_geometry/tension': 'Напряжение',

			'sidebar/material/new': 'Новый',
			'sidebar/material/copy': 'Копировать',
			'sidebar/material/paste': 'Вставить',
			'sidebar/material/slot': 'Слот',
			'sidebar/material/type': 'Type',
			'sidebar/material/uuid': 'UUID',
			'sidebar/material/name': 'Имя',
			'sidebar/material/program': 'Программа',
			'sidebar/material/info': 'Инфо',
			'sidebar/material/vertex': 'Вершина',
			'sidebar/material/fragment': 'Фрагмент',
			'sidebar/material/color': 'Цвет',
			'sidebar/material/depthPacking': 'Кодирование глубины цвета',
			'sidebar/material/roughness': 'Шероховатость',
			'sidebar/material/metalness': 'Металличность',
			'sidebar/material/sheen': 'Сиять',
			'sidebar/material/emissive': 'Эмиссионный',
			'sidebar/material/specular': 'Зеркальный',
			'sidebar/material/shininess': 'Сияние',
			'sidebar/material/clearcoat': 'Лак',
			'sidebar/material/clearcoatroughness': 'Шероховатость лака',
			'sidebar/material/vertexcolors': 'Цвета вершин',
			'sidebar/material/vertextangents': 'Касательные к вершинам',
			'sidebar/material/skinning': 'Снять покрытие',
			'sidebar/material/matcap': 'Matcap',
			'sidebar/material/map': 'Текстура',
			'sidebar/material/alphamap': 'Тектстура прозрачности',
			'sidebar/material/bumpmap': 'Рельефная текстура',
			'sidebar/material/normalmap': 'Нормальная текстура',
			'sidebar/material/clearcoatnormalmap': 'Нормальная текстура лака',
			'sidebar/material/displacemap': 'Текстура смещения',
			'sidebar/material/roughmap': 'Текстура шероховатости',
			'sidebar/material/metalmap': 'Металлическая текстура',
			'sidebar/material/specularmap': 'Зеркальная текстура',
			'sidebar/material/envmap': 'Текстура окружающей среды',
			'sidebar/material/lightmap': 'Текстура освещения',
			'sidebar/material/aomap': 'Текстура окружающей окклюзии',
			'sidebar/material/emissivemap': 'Излучающая текстура',
			'sidebar/material/gradientmap': 'Градиентная текстура',
			'sidebar/material/side': 'Сторона',
			'sidebar/material/side/front': 'Лицевая сторона',
			'sidebar/material/side/back': 'Задняя сторона',
			'sidebar/material/side/double': 'Двухсторонний',
			'sidebar/material/flatshaded': 'Плоский рендеринг',
			'sidebar/material/blending': 'Смешанный',
			'sidebar/material/blending/no': 'Нет',
			'sidebar/material/blending/normal': 'Нормальный',
			'sidebar/material/blending/additive': 'Добавлять',
			'sidebar/material/blending/subtractive': 'Вычесть',
			'sidebar/material/blending/multiply': 'Умножить',
			'sidebar/material/blending/custom': 'Персонализировать',
			'sidebar/material/opacity': 'Непрозрачность',
			'sidebar/material/transparent': 'Прозрачность',
			'sidebar/material/alphatest': 'Тест на прозрачность',
			'sidebar/material/depthtest': 'Тест глубины',
			'sidebar/material/depthwrite': 'Глубина записи',
			'sidebar/material/wireframe': 'Провод',

			'sidebar/script': 'Скрипт',
			'sidebar/script/new': 'Новый',
			'sidebar/script/edit': 'Редактировать',
			'sidebar/script/remove': 'Удалить',

			'sidebar/project': 'Проект',
			'sidebar/project/title': 'Заголовок',
			'sidebar/project/editable': 'Редактируемый',
			'sidebar/project/vr': 'VR',
			'sidebar/project/renderer': 'Рендер',
			'sidebar/project/antialias': 'Сглаживание',
			'sidebar/project/shadows': 'Тени',
			'sidebar/project/physicallyCorrectLights': 'Физически правильный свет',
			'sidebar/project/toneMapping': 'Отображение оттенков',
			'sidebar/project/materials': 'Материалы',
			'sidebar/project/Assign': 'Атрибуты',

			'sidebar/settings': 'Настройки',
			'sidebar/settings/language': 'Язык',
			'sidebar/settings/exportPrecision': 'Точность экспорта',

			'sidebar/settings/shortcuts/translate': 'Позиция',
			'sidebar/settings/shortcuts/rotate': 'Поворот',
			'sidebar/settings/shortcuts/scale': 'Масштаб',
			'sidebar/settings/shortcuts/undo': 'Назад',
			'sidebar/settings/shortcuts/focus': 'Фокус',

			'sidebar/settings/viewport/grid': 'Сетка',
			'sidebar/settings/viewport/helpers': 'Направляющие',

			'sidebar/history': 'История',
			'sidebar/history/persistent': 'Постоянный',

			'toolbar/translate': 'Позиция',
			'toolbar/rotate': 'Поворот',
			'toolbar/scale': 'Масштаб',
			'toolbar/local': 'Локальный',

			'viewport/info/objects': 'Объекты',
			'viewport/info/vertices': 'Вершины',
			'viewport/info/triangles': 'Треугольники',
			'viewport/info/frametime': 'Время кадра'

		},
		en: {
			'menubar/file': 'File',
			'menubar/file/new': 'New',
			'menubar/file/import': 'Import',
			'menubar/file/export/geometry': 'Export Geometry',
			'menubar/file/export/object': 'Export Object',
			'menubar/file/export/scene': 'Export Scene',
			'menubar/file/export/dae': 'Export DAE',
			'menubar/file/export/drc': 'Export DRC',
			'menubar/file/export/glb': 'Export GLB',
			'menubar/file/export/gltf': 'Export GLTF',
			'menubar/file/export/obj': 'Export OBJ',
			'menubar/file/export/ply': 'Export PLY',
			'menubar/file/export/ply_binary': 'Export PLY (Binary)',
			'menubar/file/export/stl': 'Export STL',
			'menubar/file/export/stl_binary': 'Export STL (Binary)',
			'menubar/file/publish': 'Publish',

			'menubar/edit': 'Edit',
			'menubar/settings': 'Settings',
			'menubar/edit/undo': 'Undo (Ctrl+Z)',
			'menubar/edit/redo': 'Redo (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': 'Clear History',
			'menubar/edit/clone': 'Clone',
			'menubar/edit/delete': 'Delete (Del)',
			'menubar/edit/fixcolormaps': 'Fix Color Maps',

			'menubar/add': 'Add',
			'menubar/add/group': 'Group',
			'menubar/add/plane': 'Plane',
			'menubar/add/box': 'Box',
			'menubar/add/circle': 'Circle',
			'menubar/add/cylinder': 'Cylinder',
			'menubar/add/ring': 'Ring',
			'menubar/add/sphere': 'Sphere',
			'menubar/add/dodecahedron': 'Dodecahedron',
			'menubar/add/icosahedron': 'Icosahedron',
			'menubar/add/octahedron': 'Octahedron',
			'menubar/add/tetrahedron': 'Tetrahedron',
			'menubar/add/torus': 'Torus',
			'menubar/add/tube': 'Труба',
			'menubar/add/torusknot': 'TorusKnot',
			'menubar/add/lathe': 'Lathe',
			'menubar/add/sprite': 'Sprite',
			'menubar/add/pointlight': 'PointLight',
			'menubar/add/spotlight': 'SpotLight',
			'menubar/add/directionallight': 'DirectionalLight',
			'menubar/add/hemispherelight': 'HemisphereLight',
			'menubar/add/ambientlight': 'AmbientLight',
			'menubar/add/perspectivecamera': 'PerspectiveCamera',
			'menubar/add/orthographiccamera': 'OrthographicCamera',

			'menubar/status/autosave': 'autosave',

			'menubar/play': 'Play',
			'menubar/play/stop': 'Stop',
			'menubar/play/play': 'Play',

			'menubar/examples': 'Examples',
			'menubar/examples/Arkanoid': 'Arkanoid',
			'menubar/examples/Camera': 'Camera',
			'menubar/examples/Particles': 'Particles',
			'menubar/examples/Pong': 'Pong',
			'menubar/examples/Shaders': 'Shaders',

			'menubar/help': 'Help',
			'menubar/help/source_code': 'Source Code',
			'menubar/help/icons': 'Icon Pack',
			'menubar/help/about': 'About',

			'sidebar/scene': 'Scene',
			'sidebar/scene/background': 'Background',
			'sidebar/scene/environment': 'Environment',
			'sidebar/scene/fog': 'Fog',

			'sidebar/properties/object': 'Object',
			'sidebar/properties/geometry': 'Geometry',
			'sidebar/properties/material': 'Material',
			'sidebar/properties/script': 'Script',

			'sidebar/object/type': 'Type',
			'sidebar/object/new': 'New',
			'sidebar/object/uuid': 'UUID',
			'sidebar/object/name': 'Name',
			'sidebar/object/position': 'Position',
			'sidebar/object/rotation': 'Rotation',
			'sidebar/object/scale': 'Scale',
			'sidebar/object/fov': 'Fov',
			'sidebar/object/left': 'Left',
			'sidebar/object/right': 'Right',
			'sidebar/object/top': 'Top',
			'sidebar/object/bottom': 'Bottom',
			'sidebar/object/near': 'Near',
			'sidebar/object/far': 'Far',
			'sidebar/object/intensity': 'Intensity',
			'sidebar/object/color': 'Color',
			'sidebar/object/groundcolor': 'Ground Color',
			'sidebar/object/distance': 'Distance',
			'sidebar/object/angle': 'Angle',
			'sidebar/object/penumbra': 'Penumbra',
			'sidebar/object/decay': 'Decay',
			'sidebar/object/shadow': 'Shadow',
			'sidebar/object/shadowBias': 'Shadow Bias',
			'sidebar/object/shadowNormalBias': 'Shadow Normal Bias',
			'sidebar/object/shadowRadius': 'Shadow Radius',
			'sidebar/object/cast': 'cast',
			'sidebar/object/receive': 'receive',
			'sidebar/object/visible': 'Visible',
			'sidebar/object/frustumcull': 'Frustum Cull',
			'sidebar/object/renderorder': 'Render Order',
			'sidebar/object/userdata': 'User data',

			'sidebar/geometry/type': 'Type',
			'sidebar/geometry/new': 'New',
			'sidebar/geometry/uuid': 'UUID',
			'sidebar/geometry/name': 'Name',
			'sidebar/geometry/bounds': 'Bounds',
			'sidebar/geometry/show_vertex_normals': 'Show Vertex Normals',

			'sidebar/geometry/box_geometry/width': 'Width',
			'sidebar/geometry/box_geometry/height': 'Height',
			'sidebar/geometry/box_geometry/depth': 'Depth',
			'sidebar/geometry/box_geometry/widthseg': 'Width Seg',
			'sidebar/geometry/box_geometry/heightseg': 'Height Seg',
			'sidebar/geometry/box_geometry/depthseg': 'Depth Seg',

			'sidebar/geometry/buffer_geometry/attributes': 'Attributes',
			'sidebar/geometry/buffer_geometry/index': 'index',

			'sidebar/geometry/circle_geometry/radius': 'Radius',
			'sidebar/geometry/circle_geometry/segments': 'Segments',
			'sidebar/geometry/circle_geometry/thetastart': 'Theta start',
			'sidebar/geometry/circle_geometry/thetalength': 'Theta length',

			'sidebar/geometry/cylinder_geometry/radiustop': 'Radius top',
			'sidebar/geometry/cylinder_geometry/radiusbottom': 'Radius bottom',
			'sidebar/geometry/cylinder_geometry/height': 'Height',
			'sidebar/geometry/cylinder_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/cylinder_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/cylinder_geometry/openended': 'Open ended',

			'sidebar/geometry/extrude_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/extrude_geometry/steps': 'Steps',
			'sidebar/geometry/extrude_geometry/depth': 'Depth',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'Bevel?',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'Thickness',
			'sidebar/geometry/extrude_geometry/bevelSize': 'Size',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'Offset',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'Segments',
			'sidebar/geometry/extrude_geometry/shape': 'Convert to Shape',

			'sidebar/geometry/geometry/vertices': 'Vertices',
			'sidebar/geometry/geometry/faces': 'Faces',

			'sidebar/geometry/dodecahedron_geometry/radius': 'Radius',
			'sidebar/geometry/dodecahedron_geometry/detail': 'Detail',

			'sidebar/geometry/icosahedron_geometry/radius': 'Radius',
			'sidebar/geometry/icosahedron_geometry/detail': 'Detail',

			'sidebar/geometry/octahedron_geometry/radius': 'Radius',
			'sidebar/geometry/octahedron_geometry/detail': 'Detail',

			'sidebar/geometry/tetrahedron_geometry/radius': 'Radius',
			'sidebar/geometry/tetrahedron_geometry/detail': 'Detail',

			'sidebar/geometry/lathe_geometry/segments': 'Segments',
			'sidebar/geometry/lathe_geometry/phistart': 'Phi start (°)',
			'sidebar/geometry/lathe_geometry/philength': 'Phi length (°)',
			'sidebar/geometry/lathe_geometry/points': 'Points',

			'sidebar/geometry/plane_geometry/width': 'Width',
			'sidebar/geometry/plane_geometry/height': 'Height',
			'sidebar/geometry/plane_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/plane_geometry/heightsegments': 'Height segments',

			'sidebar/geometry/ring_geometry/innerRadius': 'Inner radius',
			'sidebar/geometry/ring_geometry/outerRadius': 'Outer radius',
			'sidebar/geometry/ring_geometry/thetaSegments': 'Theta segments',
			'sidebar/geometry/ring_geometry/phiSegments': 'Phi segments',
			'sidebar/geometry/ring_geometry/thetastart': 'Theta start',
			'sidebar/geometry/ring_geometry/thetalength': 'Theta length',

			'sidebar/geometry/shape_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/shape_geometry/extrude': 'Extrude',

			'sidebar/geometry/sphere_geometry/radius': 'Radius',
			'sidebar/geometry/sphere_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/sphere_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/sphere_geometry/phistart': 'Phi start',
			'sidebar/geometry/sphere_geometry/philength': 'Phi length',
			'sidebar/geometry/sphere_geometry/thetastart': 'Theta start',
			'sidebar/geometry/sphere_geometry/thetalength': 'Theta length',

			'sidebar/geometry/torus_geometry/radius': 'Radius',
			'sidebar/geometry/torus_geometry/tube': 'Труба',
			'sidebar/geometry/torus_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torus_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torus_geometry/arc': 'Arc',

			'sidebar/geometry/torusKnot_geometry/radius': 'Radius',
			'sidebar/geometry/torusKnot_geometry/tube': 'Труба',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torusKnot_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torusKnot_geometry/p': 'P',
			'sidebar/geometry/torusKnot_geometry/q': 'Q',

			'sidebar/geometry/tube_geometry/path': 'Path',
			'sidebar/geometry/tube_geometry/radius': 'Radius',
			'sidebar/geometry/tube_geometry/tube': 'Труба',
			'sidebar/geometry/tube_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/tube_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/tube_geometry/closed': 'Closed',
			'sidebar/geometry/tube_geometry/curvetype': 'Curve Type',
			'sidebar/geometry/tube_geometry/tension': 'Tension',

			'sidebar/material/new': 'New',
			'sidebar/material/copy': 'Copy',
			'sidebar/material/paste': 'Paste',
			'sidebar/material/slot': 'Slot',
			'sidebar/material/type': 'Type',
			'sidebar/material/uuid': 'UUID',
			'sidebar/material/name': 'Name',
			'sidebar/material/program': 'Program',
			'sidebar/material/info': 'Info',
			'sidebar/material/vertex': 'Vertex',
			'sidebar/material/fragment': 'fragment',
			'sidebar/material/color': 'Color',
			'sidebar/material/depthPacking': 'Depth Packing',
			'sidebar/material/roughness': 'Roughness',
			'sidebar/material/metalness': 'Metalness',
			'sidebar/material/sheen': 'Sheen',
			'sidebar/material/emissive': 'Emissive',
			'sidebar/material/specular': 'Specular',
			'sidebar/material/shininess': 'Shininess',
			'sidebar/material/clearcoat': 'Clearcoat',
			'sidebar/material/clearcoatroughness': 'Clearcoat Roughness',
			'sidebar/material/vertexcolors': 'Vertex Colors',
			'sidebar/material/vertextangents': 'Vertex Tangents',
			'sidebar/material/skinning': 'Skinning',
			'sidebar/material/matcap': 'Matcap',
			'sidebar/material/map': 'Map',
			'sidebar/material/alphamap': 'Alpha Map',
			'sidebar/material/bumpmap': 'Bump Map',
			'sidebar/material/normalmap': 'Normal Map',
			'sidebar/material/clearcoatnormalmap': 'Clearcoat Normal Map',
			'sidebar/material/displacemap': 'Displace Map',
			'sidebar/material/roughmap': 'Rough. Map',
			'sidebar/material/metalmap': 'Metal. Map',
			'sidebar/material/specularmap': 'Specular Map',
			'sidebar/material/envmap': 'Env Map',
			'sidebar/material/lightmap': 'Light Map',
			'sidebar/material/aomap': 'AO Map',
			'sidebar/material/emissivemap': 'Emissive Map',
			'sidebar/material/gradientmap': 'Gradient Map',
			'sidebar/material/side': 'Side',
			'sidebar/material/side/front': 'Front',
			'sidebar/material/side/back': 'Back',
			'sidebar/material/side/double': 'Double',
			'sidebar/material/flatshaded': 'Flat Shaded',
			'sidebar/material/blending': 'Blending',
			'sidebar/material/blending/no': 'No',
			'sidebar/material/blending/normal': 'Normal',
			'sidebar/material/blending/additive': 'Additive',
			'sidebar/material/blending/subtractive': 'Subtractive',
			'sidebar/material/blending/multiply': 'Multiply',
			'sidebar/material/blending/custom': 'Custom',
			'sidebar/material/opacity': 'Opacity',
			'sidebar/material/transparent': 'Transparent',
			'sidebar/material/alphatest': 'Alpha Test',
			'sidebar/material/depthtest': 'Depth Test',
			'sidebar/material/depthwrite': 'Depth Write',
			'sidebar/material/wireframe': 'Wireframe',

			'sidebar/script': 'Script',
			'sidebar/script/new': 'New',
			'sidebar/script/edit': 'Edit',
			'sidebar/script/remove': 'Remove',

			'sidebar/project': 'Project',
			'sidebar/project/title': 'Title',
			'sidebar/project/editable': 'Editable',
			'sidebar/project/vr': 'VR',
			'sidebar/project/renderer': 'Renderer',
			'sidebar/project/antialias': 'Antialias',
			'sidebar/project/shadows': 'Shadows',
			'sidebar/project/physicallyCorrectLights': 'Physical lights',
			'sidebar/project/toneMapping': 'Tone mapping',
			'sidebar/project/materials': 'Materials',
			'sidebar/project/Assign': 'Assign',

			'sidebar/settings': 'Settings',
			'sidebar/settings/language': 'Language',
			'sidebar/settings/exportPrecision': 'Export Precision',

			'sidebar/settings/shortcuts/translate': 'Translate',
			'sidebar/settings/shortcuts/rotate': 'Rotate',
			'sidebar/settings/shortcuts/scale': 'Scale',
			'sidebar/settings/shortcuts/undo': 'Undo',
			'sidebar/settings/shortcuts/focus': 'Focus',

			'sidebar/settings/viewport/grid': 'Grid',
			'sidebar/settings/viewport/helpers': 'Helpers',

			'sidebar/history': 'History',
			'sidebar/history/persistent': 'persistent',

			'toolbar/translate': 'Translate',
			'toolbar/rotate': 'Rotate',
			'toolbar/scale': 'Scale',
			'toolbar/local': 'Local',

			'viewport/info/objects': 'Objects',
			'viewport/info/vertices': 'Vertices',
			'viewport/info/triangles': 'Triangles',
			'viewport/info/frametime': 'Frametime'

		}
	};

	return {

		getKey: function ( key ) {

			return values[ language ][ key ] || '???';

		}

	};

}

export { Strings };
